#!/bin/bash

echo "Lightning Pass Screenshot Setup"
echo "================================"
echo ""
echo "Please save the 3 Lightning Pass images you just uploaded as:"
echo ""
echo "1. lightning-venues.png     (Live Venues browse page)"
echo "2. lightning-purchase.png   (Ticket purchase flow)"
echo "3. lightning-dashboard.png  (Venue dashboard)"
echo ""
echo "Save them to: /Users/pheonix/portfolio-seo/"
echo ""
echo "Then run:"
echo "  cd /Users/pheonix/portfolio-seo"
echo "  git add lightning*.png"
echo "  git commit -m 'Add Lightning Pass screenshots'"
echo "  git push origin main"
echo ""
echo "The carousel is already configured to display them!"
